### ISSUE TITLE
Why would a component have a SendEvent?

### ISSUE THREAD

**Issue by bayganik** [PeteyChan/SimpleECS#23]
Thank you for the new SimpleECS.  Looking at the tutorial, I see your BulletComonent sending an event for <BulletCollisionEvent>.  

How does this get triggered to send the event?

**Comment by PeteyChan** [comment]
I could of written that better, it's using the inbuilt UnityEvent OnTriggerEnter which gets called whenever a trigger enters a collider. Since Unity uses magic methods to call physics and animation events the logic unfortunately needs to be coupled to the component instead of a system.
