### ISSUE TITLE
OnSet old data

### ISSUE THREAD

**Issue by DigitalOxygen58** [PeteyChan/SimpleECS#27]
Hi again! In last (or so) update u've removed OnSet callback overload (Entity e, T newComponent), now its only (Entity e, T oldComponent, T newComponent). Sometimes (most of the time actually) we simply dont need previous state of component, so this causes no more than writing additional code. Could you please give us an ability to use both overloads? 
I know we can just use method codegeneration to create a method with proper parameters, but still we have a dozen of code written in old style, so updating to new version would force us to refactor code slightly

**Comment by PeteyChan** [comment]
No worries, pretty easy to add back.
